# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83c98698034377559f63288266ef3dab6eef00c8b436f49e18d7e7a743e03cba22de0da163c6e401f3a4a42c092846a3a74b64c8432b4cdd4fd6ce828f426474

test:
  secret_key_base: 8f022406e3d02c695f659e1a6a43f50df8ff9f28ef16b2902f10d1eaf9258ed02496418de7051f78c49cf675ccafabf3553981f4d501c46f0cd8cbb22627cb6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
